### ISSUE TITLE
Necesita un verdadero CDN

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/kimera#1]
No se debe de usar github como CDN, mi navegador me da el siguiente error en consola.

> El recurso de “https://raw.githubusercontent.com/JorgeAntrax/kimera/master/css/kimera.min.css” fue bloqueado por diferencia de tipo MIME (X-Content-Type-Options: nosniff).

Por ejemplo: https://codepen.io/javatlacati/pen/pWMpdx

**Comment by leoquintara** [comment]
Estoy al tanto ese método es provisional, ya q no tengo experiencia con cdn's
Estoy investigando, gracias bro

**Comment by paramirez** [comment]
Estaré al tanto de la complementación de un CDN

**Comment by javatlacati** [comment]
Requisitos para CDNJS... popularidad 😢 

https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets

En un mes si no consigues nada, me gustaria comprar un certificado https para guardar el minificado en mi portal, tal vez no siempre pueda actualizarlo, pero servira para darlo a conocer, asi que si no hallaras otra solucion no dudes en contactarme.

**Comment by leoquintara** [comment]
Espero que ya esté listo, no sé qué tan bueno sea jsdelivr ya que fue la única opción que pude configurar 

http://cdn.jsdelivr.net/npm/kimera@0.2.3/css/kimera.min.css

**Comment by leoquintara** [comment]
nuevo link del cdn

https://cdn.jsdelivr.net/gh/JorgeAntrax/kimera@0.2.4/css/kimera.css
