### ISSUE TITLE
¿Por que no utilizo gh-page para la documentación?

### ISSUE THREAD

**Issue by leninalbertolp** [JorgeAntrax/kimera#11]
Hola, felicitaciones por este nuevo framework lo tengo reservado para futuros proyectos. Mi pregunta es. Por qué no usó gh-page para alojar la documentación del proyecto, no se si te habrás fijado que 000webhost te inserto una publicidad que ocupa el 30% del viewport en lo personal es un tanto molesto para mi ya que me dificulta leer a gusto dicha documentación. De resto todo esta excelente seguid adelante.

**Comment by leoquintara** [comment]
Hola gracias por tu comentario justamente estoy preparando todo para git hub pages creo en unos cuantos minutos público el link, para evitar esa publicidad mientras consigo un hosting, gracias.

**Comment by leoquintara** [comment]
Listo amigo ya puedes revisar bien la documentación

**Comment by leoquintara** [comment]
Ya solucioné tanto el link

kimera.comli.com

Y también la puedes visualizar en github Pagés

https://jorgeantrax.github.io/kimeracss
