### ISSUE TITLE
Is jQuery dependence really necessary?

### ISSUE THREAD

**Issue by TheMushrr00m** [JorgeAntrax/kimera#12]
Hi, i just want to contribute with this project, i find it great, but i have a really issue with this topic.

I mean, it's 2018, vanilla js it's on a great path of evolution, why following using jQuery?

**Comment by leoquintara** [comment]
Hello, I'm glad you like this project, I'm really going to replace jquery with vanilla, my knowledge of javascript is not very advanced, maybe it could be your first contribution to the project, and welcome.

**Comment by TheMushrr00m** [comment]
Sure, i'm going to work on it.

**Comment by leoquintara** [comment]
for now I have the code for integration modular, and the tabs
