### ISSUE TITLE
Sidebar is no longer a sidebar

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/kimera#2]
Se perdió la funcionalidad de barra lateral en el cambio de versión.

```
<layout>
    <headerclass="color-primary">@content</header>
    <navbarclass="color-warning">@content</navbar>
    <sidebarclass="color-info">@content</sidebar>
    <mainclass="color-success">@content</main>
    <footerclass="color-danger">@content</footer>
</layout>
```

Imagino que se puede recrear con `is-dashboard`, pero forza a layouts internos y le quita simplicidad, aumentando el tiempo requerido para lograr una interfaz.

**Comment by leoquintara** [comment]
Ya quedó listo! Grid layout 

kimera.comli.com/kimera
