### ISSUE TITLE
Add maintenance badge

### ISSUE THREAD

**Issue by javatlacati** [JorgeAntrax/kimera#20]
It will be a nice idea to add the is maintained badge in the readme so people can know how long is taking us in average to solve issues reported.

They look like this:
[![Average time to resolve an issue](http://isitmaintained.com/badge/resolution/JorgeAntrax/kimera.svg)](http://isitmaintained.com/project/JorgeAntrax/kimera "Average time to resolve an issue")
[![Percentage of issues still open](http://isitmaintained.com/badge/open/JorgeAntrax/kimera.svg)](http://isitmaintained.com/project/JorgeAntrax/kimera "Percentage of issues still open")

You can get the code for the badges from http://isitmaintained.com/project/JorgeAntrax/kimera

**Comment by leoquintara** [comment]
Ok is ready!

**Comment by javatlacati** [comment]
I still don't see the maintenance badge in the readme so I'm reopening it.

**Comment by leoquintara** [comment]
Ahora si
