### ISSUE TITLE
Ops..

### ISSUE THREAD

**Issue by ghost** [JorgeAntrax/kimera#23]
Hi to you. Did you do an investigation before choosing the name? that since 2015/2016 there is already a kimera css framework?

I recommend to change.

https://github.com/ShapeGroup/KiMERA-WEB-FRAMEWORK/commits/KiMERA-GitHub
https://github.com/ShapeGroup/Kimera-css-framework-2.X

**Comment by leoquintara** [comment]
Hello, I did not really do a previous investigation when choosing the name, I simply had an idea in mind and started to develop it. Thanks for your comment

**Comment by ghost** [comment]
we, however, yes! and we branded it.
It's all OK. We don't want to take "heavy actions" but it would be advisable to change the name-in the shortest possible time- of your framework (being competitive!).

We thank you.

Shape agency staff

**Comment by JorgeAntrax** [comment]
@ShapeGroup ok Give me 3 days to investigate and change the name, Thank you.

**Comment by leoquintara** [comment]
as heavy actions?

**Comment by ghost** [comment]
"Lawsuits".
Kimera framework is a trademark registered in the name of a company. However, there does not seem to be a case of quarreling becouse doesn't exist a way to control the "variations of names for the same activity" and these are things that can happen in the online world.

We're online even before 2015, so you're only sent to choose a different name because we're doing too much work and so we both get lost.

In friendly.... Thank you.

and good work! ;)

**Comment by leoquintara** [comment]
thank you, do not worry and change the name of the framework, now called Level CSS, if this usually happens it's good to talk about it before. regards

**Comment by ghost** [comment]
Perfect.

Sorry ... we understand. We have gone the same way with "webpack" name (the original kimera on the 2014).

Greetings! Bye!

**Comment by leoquintara** [comment]
Thanks you
